-- Add DISPUTE_VOTING and MILESTONE_AUTO_APPROVED to NotificationType enum
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'DISPUTE_VOTING';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'MILESTONE_AUTO_APPROVED';
